name: Model Monitoring

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install evidently
      - name: Run model monitoring
        run: |
          python src/core/ml/monitoring.py
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: model-monitoring-report
          path: reports/model_monitoring.html